### PR TITLE
Revert "Feature/timvelasquez"

### PR DESCRIPTION
**Pull request by MrAwesome2127**
Reverts MrAwesome2127/LetsGoTakeADumpster#30

### CODE REVIEW

**Review by budtriplett — APPROVED** [review]
Looks just as good as the day I saw it!

**Review by Nebbs82 — APPROVED** [review]
You could really do better, and you know this

**Review by cpotter88 — APPROVED** [review]
It'll work

**Review by delta-black5 — APPROVED** [review]
All good

**Pull request merged**
