### PR TITLE
Body Layout HTMl

### PR DESCRIPTION
**Pull request by budtriplett**
created a basic body layout for main page.

### CODE REVIEW

**Review by Nebbs82 — CHANGES_REQUESTED** [review]
The changes you made to the image calls didn't get added because this was in a different terminal

**Comment by delta-black5** [comment]
accepts

**Review by Nebbs82 — CHANGES_REQUESTED** [review]
Still need to fix the image calls and make them ..assets

**Review by Nebbs82 — APPROVED** [review]
Got it

**Review by delta-black5 — APPROVED** [review]
all good

**Pull request merged**
