### PR TITLE
Contact Form JS Added

### PR DESCRIPTION
**Pull request by budtriplett**
I made the form on the contact us page interactive as well as it will store all input into local storage. I've attached an image that shows I've tried out the local storage and it worked on my end.

Image 11-4-24 at 4 21 PM

### CODE REVIEW

**Review by Nebbs82 — APPROVED** [review]
You done did it now!

**Review by MrAwesome2127 — APPROVED** [review]
Good work

**Review by cpotter88 — APPROVED** [review]
Fantastic

**Review by delta-black5 — APPROVED** [review]
Good

**Pull request merged**
